### ISSUE TITLE
How to check section header is open or not

### ISSUE THREAD

**Issue by dongawli** [cuiyueshuai/react-native-expandable-section-list#3]
Hi Cuiyueshuai,

Thank you for nice expandable section list component. Really like the UI and very simplified. 
I want to know is there any property by which we can check whether section is Open or Close? 
I need to show the + / - in header based on section is open or not. Please find the attached screenshot - https://hub.mangoapps.com/sf/MTI0MjE4XzE0MzQyOTk

Thank you,
-Vijay

**Comment by cuiyueshuai** [comment]
@dongawli Thank you, oh ,sorry, This is my bug, and I fixed, you can update the `react-native-expandable-section-list` to v1.0.4

the callback function of `renderSectionHeaderX` add Third parameter 'state': the state of current section, current section is open or not, 

In addition, The callback function of `headerOnPress ` is called when the section header is clicked, and it will return two arguments, 
first paramter: the index of current section
Second parameter: the state of current section, current section is open or not

**Comment by dongawli** [comment]
Thank you for quick response.. 
newly modified function renderSectionHeaderX () solved by issue..
